// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4jldKs5LKFTuBLBWpBXPajZkKo2QHNUM',
    appId: '1:83264805521:web:c2dc082c0e67e66fbebd30',
    messagingSenderId: '83264805521',
    projectId: 'fir-authentication-ab7c1',
    authDomain: 'fir-authentication-ab7c1.firebaseapp.com',
    storageBucket: 'fir-authentication-ab7c1.appspot.com',
    measurementId: 'G-6DSL3HBWM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9w9vCdo8ZgNyaLctq8pVDRRmLeaQieWU',
    appId: '1:83264805521:android:576b1cb733a0e7bdbebd30',
    messagingSenderId: '83264805521',
    projectId: 'fir-authentication-ab7c1',
    storageBucket: 'fir-authentication-ab7c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwpnHjrBJnaC6kMLe0pR4HEWMbCfggzd4',
    appId: '1:83264805521:ios:c761da4405196c3abebd30',
    messagingSenderId: '83264805521',
    projectId: 'fir-authentication-ab7c1',
    storageBucket: 'fir-authentication-ab7c1.appspot.com',
    androidClientId: '83264805521-87s3bad2743lq9c48eeh9u5r8hcq529u.apps.googleusercontent.com',
    iosClientId: '83264805521-35c3slmdbpgi7q7mfpktu8cofme5dugf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwpnHjrBJnaC6kMLe0pR4HEWMbCfggzd4',
    appId: '1:83264805521:ios:c761da4405196c3abebd30',
    messagingSenderId: '83264805521',
    projectId: 'fir-authentication-ab7c1',
    storageBucket: 'fir-authentication-ab7c1.appspot.com',
    androidClientId: '83264805521-87s3bad2743lq9c48eeh9u5r8hcq529u.apps.googleusercontent.com',
    iosClientId: '83264805521-35c3slmdbpgi7q7mfpktu8cofme5dugf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth1',
  );
}
